service: scrapbox-codesync
frameworkVersion: "2"
plugins:
  - serverless-localstack
  - serverless-dotenv-plugin
  - serverless-cloudformation-changesets

custom:
  defaultRegion: ap-northeast-1
  defaultStage: local
  localstack:
    debug: true
    autostart: true
    lambda:
      mountCode: true
    docker:
      sudo: false
    stages:
      - local
      - dev
    endpointFile: localstack_endpoints.json
  profile: slsfw-${self:provider.stage} # stageに応じたprofile名を指定
  environment:
    SLS_STAGE: ${self:provider.stage}

provider:
  name: aws
  runtime: nodejs12.x
  timeout: 300
  profile: ${opt:profile, self:custom.profile}
  region: ${opt:region, self:custom.defaultRegion}

functions:
  hello:
    handler: handler.hello
    layers:
      - { Ref: ChromeLambdaLayer }
    environment: ${self:custom.environment}

package:
  exclude:
    - node_modules/serverless/**
    - node_modules/chrome-aws-lambda/**
    - chrome-aws-lambda/**

layers:
  chrome:
    package:
      artifact: ./chrome-aws-lambda/chrome_aws_lambda.zip
