service: scrapbox-codesync

frameworkVersion: "2"

plugins:
  - serverless-dotenv-plugin
  - serverless-cloudformation-changesets

useDotenv: true

custom:
  defaultRegion: ap-northeast-1
  defaultStage: local
  profile: slsfw-${self:provider.stage} # stageに応じたprofile名を指定
  projectName: ${opt:projectName, env:PROJECT_NAME}
  secretToken: ${opt:secretToken, env:SECRET_TOKEN}
  scrapboxConnectSid: ${opt:scrapboxConnectSid, env:SCRAPBOX_CONNECT_SID}
  environment:
    SLS_STAGE: ${self:provider.stage}
    PROJECT_NAME: ${self:custom.projectName}
    SECRET_TOKEN: ${self:custom.secretToken}
    SCRAPBOX_CONNECT_SID: ${self:custom.scrapboxConnectSid}
  request:
    template:
      application/json:
        method: $context.httpMethod,
        body: $input.json('$'),
        headers:
          #foreach($param in $input.params().header.keySet())
          $param: $util.escapeJavaScript($input.params().header.get($param))
          #if($foreach.hasNext),#end
          #end

provider:
  name: aws
  runtime: nodejs12.x
  timeout: 30
  profile: ${opt:profile, self:custom.profile}
  region: ${opt:region, self:custom.defaultRegion}
  stage: ${opt:stage, self:custom.defaultStage}
  apiGateway:
    shouldStartNameWithService: true

functions:
  sync:
    handler: handler.sync
    events:
      - http:
          path: scrapbox/code/sync
          method: post
    layers:
      - { Ref: ChromeLambdaLayer }
    environment: ${self:custom.environment}
package:
  exclude:
    - node_modules/serverless/**
    - node_modules/chrome-aws-lambda/**
    - chrome-aws-lambda/**

layers:
  chrome:
    package:
      artifact: ./layers/chrome_aws_lambda.zip
