service: scrapbox-codesync

frameworkVersion: "2"

plugins:
  - serverless-dotenv-plugin
  - serverless-cloudformation-changesets

useDotenv: true

custom:
  defaultRegion: ap-northeast-1
  defaultStage: local
  profile: slsfw-${self:provider.stage} # stageに応じたprofile名を指定
  projectName: ${env.PROJECT_NAME}
  environment:
    SLS_STAGE: ${self:provider.stage}
    PROJECT_NAME: ${self:custom.projectName}

provider:
  name: aws
  runtime: nodejs12.x
  timeout: 300
  profile: ${opt:profile, self:custom.profile}
  region: ${opt:region, self:custom.defaultRegion}
  stage: ${opt:stage, self:custom.defaultStage}
  apiGateway:
    shouldStartNameWithService: true

functions:
  sync:
    handler: handler.sync
    events:
      - http:
          path: scrapbox/code/sync
          method: post
    layers:
      - { Ref: ChromeLambdaLayer }
    environment: ${self:custom.environment}
package:
  exclude:
    - node_modules/serverless/**
    - node_modules/chrome-aws-lambda/**
    - chrome-aws-lambda/**

layers:
  chrome:
    package:
      artifact: ./layers/chrome_aws_lambda.zip
