service: scrapbox-codesync

frameworkVersion: "2"

plugins:
  - serverless-dotenv-plugin
  - serverless-cloudformation-changesets

useDotenv: true

custom:
  defaultRegion: ap-northeast-1
  defaultStage: local
  profile: slsfw-${self:provider.stage} # stageに応じたprofile名を指定
  environment:
    SLS_STAGE: ${self:provider.stage}
    PROJECT_NAME: ${opt:projectName, env:PROJECT_NAME}
    SECRET_TOKEN: ${opt:secretToken, env:SECRET_TOKEN}
    SCRAPBOX_CONNECT_SID: ${opt:scrapboxConnectSid, env:SCRAPBOX_CONNECT_SID}
    USER_CSS_EYECATCH_URL: ${env:USER_CSS_EYECATCH_URL}
    USER_SCRIPT_EYECATCH_URL: ${env:USER_SCRIPT_EYECATCH_URL}

  request:
    template:
      application/json:
        method: $context.httpMethod,
        body: $input.json('$'),
        headers:
          #foreach($param in $input.params().header.keySet())
          $param: $util.escapeJavaScript($input.params().header.get($param))
          #if($foreach.hasNext),#end
          #end

provider:
  name: aws
  runtime: nodejs12.x
  timeout: 900
  profile: ${opt:profile, self:custom.profile}
  region: ${opt:region, self:custom.defaultRegion}
  stage: ${opt:stage, self:custom.defaultStage}
  apiGateway:
    shouldStartNameWithService: true

functions:
  sync:
    handler: handler.sync
    layers:
      - { Ref: ChromeLambdaLayer }
    environment: ${self:custom.environment}
  receive:
    handler: handler.receive
    events:
      - http:
          path: scrapbox/code/receive
          method: post
    layers:
      - { Ref: ChromeLambdaLayer }
    environment: ${self:custom.environment}

package:
  exclude:
    - node_modules/serverless/**
    - node_modules/chrome-aws-lambda/**
    - chrome-aws-lambda/**

layers:
  chrome:
    package:
      artifact: ./layers/chrome_aws_lambda.zip
